#%RAML 1.0
title: MuleSoft WebCrawler API
description: API for web crawling and data extraction
version: 1.0.0

baseUri: http://localhost:{port}
baseUriParameters:
  port:
    default: "8081"

types:
  Node:
    type: object
    properties:
      url:
        type: string
        description: The URL of the resource
        required: true
      children:
        type: array
        description: A list of child objects, each with its own URL and potential children
        items:
          type: Node
    additionalProperties: false
    
/page:
  get:
    queryParameters:
      url:
        type: string
        required: true
      outputFormat:
        type: string
        enum: [HTML, TEXT, MARKDOWN]
        required: true
      connection:
        type: string
        default: http
        required: false
      waitOnPageLoad:
        type: number
        required: false
      waitForXPath:
        type: string
        required: false
      extractShadowDom:
        type: boolean
        required: false
      shadowDomHostXPath:
        type: string
        required: false
    responses:
      200:
        description: Page content retrieved successfully

/insights:
  get:
    queryParameters:
      url:
        type: string
        required: true
      connection:
        type: string
        default: http
        required: false
      waitOnPageLoad:
        type: number
        required: false
    responses:
      200:
        description: Page insights retrieved successfully

/sitemap:
  get:
    queryParameters:
      url:
        type: string
        required: true
      connection:
        type: string
        default: http
        required: false
      depth:
        type: integer
      waitOnPageLoad:
        type: number
        required: false
    responses:
      200:
        description: Sitemap generated successfully
        body:
          application/xml:
            example: |
              <?xml version="1.0" encoding="UTF-8"?>
              <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
                <url>
                  <loc>http://example.com/</loc>
                  <priority>1.0</priority>
                </url>
              </urlset>

/metatag:
  get:
    queryParameters:
      url:
        type: string
        required: true
      connection:
        type: string
        default: http
        required: false
      waitOnPageLoad:
        type: number
        required: false
    responses:
      200:
        description: Meta tags retrieved successfully

/image:
  get:
    queryParameters:
      url:
        type: string
        required: true
      downloadLocation:
        type: string
        required: true
      connection:
        type: string
        default: http
        required: false
      waitOnPageLoad:
        type: number
        required: false
    responses:
      200:
        description: Images downloaded successfully

/document:
  get:
    queryParameters:
      url:
        type: string
        required: true
      downloadLocation:
        type: string
        required: true
      connection:
        type: string
        default: http
        required: false
      waitOnPageLoad:
        type: number
        required: false
    responses:
      200:
        description: Documents downloaded successfully

/crawl-full-scan:
  get:
    queryParameters:
      url:
        type: string
        required: true
      outputFormat:
        type: string
        enum: [HTML, TEXT, MARKDOWN]
        required: true
      depth:
        type: integer
      downloadLocation:
        type: string
      connection:
        type: string
        default: http
        required: false
      waitOnPageLoad:
        type: number
        required: false
    responses:
      200:
        description: Website crawled successfully
        
/crawl-streaming:
  get:
    queryParameters:
      url:
        type: string
        required: true
      outputFormat:
        type: string
        enum: [HTML, TEXT, MARKDOWN]
        required: true
      depth:
        type: integer
      connection:
        type: string
        default: http
        required: false
      waitOnPageLoad:
        type: number
        required: false
    responses:
      200:
        description: Website crawled successfully
        

/search:
  get:
    headers:
      Serper-Api-Key:
        type: string
        required: true
    queryParameters:
      query:
        type: string
        required: true
    responses:
      200:
        description: Search results retrieved successfully
